# Site settings
title: preCICE
description: > # this means to ignore newlines until "baseurl:"
  preCICE (Precise Code Interaction Coupling Environment) is an open-source coupling library for partitioned simulations of multi-physics scenarios such as fluid-structure interaction or fluid-structure-acoustic interaction.
baseurl: "" # the subpath of your site, e.g. /blog/

# Build settings
markdown: kramdown

collections:
  - publications
  - testimonials
  - codes

plugins:
  - jekyll-mentions
  - jekyll-sitemap

sass:
  style: compressed

exclude: [vendor] # Fix for travis
